/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 retro-computer.glb -T 
Files: retro-computer.glb [536.66KB] > D:\PROGRAMS\PORTFOLIO\mac_book_app\public\models\retro-computer-transformed.glb [31.52KB] (94%)
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export default function RetroComputer(props) {
  const { nodes, materials } = useGLTF('/models/retro-computer-transformed.glb')
  // texture
  const texture = ('/screen.png')
  return (
    <group {...props} dispose={null}>
      <group position={[0.033, -0.24, 3.64]} rotation={[0, -0.833, 0]} scale={[0.267, 0.09, 0.153]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh geometry={nodes['wire-whole'].geometry} material={nodes['wire-whole'].material} position={[0.14, -0.301, 3.851]} rotation={[Math.PI / 2, 0, 0.833]} scale={0.009} />
    </group>
  )
}

useGLTF.preload('/retro-computer-transformed.glb')
